# Generated by Django 5.1.2 on 2024-12-02 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_campo', models.CharField(max_length=200)),
                ('tipo_interno', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['tipo_de_campo', 'tipo_interno'],
            },
        ),
        migrations.CreateModel(
            name='TipoColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_color', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['tipo_de_color'],
            },
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_material', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['tipo_de_material'],
            },
        ),
        migrations.CreateModel(
            name='TipoParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_parte', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('mostrar_en_landing_page', models.BooleanField(blank=True, default=True)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='catalogo.categoriaproducto')),
            ],
            options={
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='OpcionColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('tipo_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='catalogo.tipocolor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OpcionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('tipo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='catalogo.tipomaterial')),
            ],
            options={
                'ordering': ['material'],
            },
        ),
    ]
