# Generated by Django 5.1.2 on 2025-03-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_estadopersonalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcioncolor',
            name='imagen',
            field=models.FileField(blank=True, help_text='Tamaño recomendado de 100x45', null=True, upload_to='color'),
        ),
    ]
