# Generated by Django 5.1.2 on 2025-04-13 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_opcioncolor_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionmaterial',
            name='imagen',
            field=models.FileField(blank=True, help_text='Tamaño recomendado de 100x45', null=True, upload_to='opcioncatalogo'),
        ),
        migrations.AlterField(
            model_name='opcionmaterial',
            name='material',
            field=models.CharField(max_length=50, verbose_name='Opción'),
        ),
        migrations.AlterField(
            model_name='opcionmaterial',
            name='tipo_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='catalogo.tipomaterial', verbose_name='Catálogo'),
        ),
        migrations.AlterField(
            model_name='tipomaterial',
            name='tipo_de_material',
            field=models.CharField(max_length=200, verbose_name='Catálogo'),
        ),
    ]
