# Generated by Django 5.1.2 on 2025-04-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_opcionmaterial_imagen_alter_opcionmaterial_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcioncolor',
            name='codigo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
