# Generated by Django 5.1.2 on 2025-04-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_opcioncolor_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcioncolor',
            name='codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
