# Generated by Django 5.1.2 on 2025-04-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_opcioncolor_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcioncolor',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='opcioncolor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opcioncolor',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
