# Generated by Django 5.1.2 on 2025-04-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_opcioncolor_options_opcioncolor_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcionmaterial',
            options={'ordering': ['orden', 'material']},
        ),
        migrations.AddField(
            model_name='opcionmaterial',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
