# Generated by Django 5.1.2 on 2024-12-02 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('posicion', models.PositiveSmallIntegerField(help_text='Orden de la parte en que se realizará la personalización del producto')),
                ('tipo_de_parte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipoparte')),
            ],
            options={
                'ordering': ['posicion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CampoParteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('posicion', models.PositiveSmallIntegerField(help_text='Orden del campo en que se realizará la personalización del producto')),
                ('id_svg', models.CharField(blank=True, help_text='ID del elemento de la svg correspondiente a la personalización del producto', max_length=100)),
                ('opciones_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipocolor')),
                ('opciones_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipomaterial')),
                ('tipo_de_campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipocampo')),
                ('parte_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='producto.parteproducto')),
            ],
            options={
                'ordering': ['posicion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.FileField(help_text="Archivo *.sgv con los elementos en 'id' correspondientes a la imagen del producto a personalizar", upload_to='producto/')),
                ('categorias', models.ManyToManyField(blank=True, related_name='productos', to='catalogo.categoriaproducto')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='parteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='producto.producto'),
        ),
    ]
