# Generated by Django 5.1.2 on 2024-12-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mostrar_en_galeria',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
