# Generated by Django 5.1.2 on 2025-04-01 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campoparteproducto',
            name='parte_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='producto.parteproducto'),
        ),
        migrations.CreateModel(
            name='GrupoCampos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('posicion', models.PositiveSmallIntegerField(help_text='Orden del campo en que se realizará la personalización del producto')),
                ('parte_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruposdecampos', to='producto.parteproducto')),
            ],
            options={
                'ordering': ['posicion', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='campoparteproducto',
            name='grupo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='producto.grupocampos'),
        ),
    ]
