# Generated by Django 5.1.2 on 2025-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_alter_campoparteproducto_parte_producto_grupocampos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupocampos',
            name='posicion',
            field=models.PositiveSmallIntegerField(help_text='Orden del grupo de campos en que se realizará la personalización del producto'),
        ),
    ]
