# Generated by Django 5.1.2 on 2025-04-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_opcioncolor_imagen'),
        ('producto', '0006_alter_grupocampos_posicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campoparteproducto',
            name='opciones_color',
        ),
        migrations.AddField(
            model_name='parteproducto',
            name='paletas_de_color',
            field=models.ManyToManyField(blank=True, null=True, to='catalogo.tipocolor'),
        ),
    ]
