# Generated by Django 5.1.2 on 2025-04-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_opcioncolor_imagen'),
        ('producto', '0007_remove_campoparteproducto_opciones_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parteproducto',
            name='paletas_de_color',
            field=models.ManyToManyField(blank=True, to='catalogo.tipocolor'),
        ),
    ]
