# Generated by Django 5.1.2 on 2025-04-22 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_opcioncolor_options_opcioncolor_activo_and_more'),
        ('producto', '0008_alter_parteproducto_paletas_de_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campoparteproducto',
            name='opciones_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipomaterial', verbose_name='Opciones de Producto'),
        ),
    ]
