# Generated by Django 5.1.2 on 2024-12-12 20:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_estadopersonalizacion'),
        ('personalizacion_producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='actualizacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='estado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='catalogo.estadopersonalizacion'),
            preserve_default=False,
        ),
    ]
