# Generated by Django 5.1.2 on 2024-12-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizacion_producto', '0002_personalizacion_actualizacion_personalizacion_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalizacion',
            options={'ordering': ['estado__estado', 'actualizacion']},
        ),
        migrations.AlterModelOptions(
            name='personalizaciondetalle',
            options={'ordering': ['personalizacion', 'campo', 'valor']},
        ),
        migrations.AlterField(
            model_name='personalizacion',
            name='actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
